### ISSUE TITLE
RChain Vs Cardano Claims and Comparison

### ISSUE THREAD

**Issue by jeremybeal11** [rchain/bounties#728]
After working with @patrick727.  I have received a request to do a claims and comparison report on Cardano. 

Here is the one i did with [Cardano.](https://docs.google.com/document/d/1-MAwHS5gtOt1ugsG0Go0Uf23sgWgaa0lwPXQouUDf_U/edit)
This was the second case study I've done and we were going to use with the bounty program.
Hours spent: 10
Rate proposed: $40hr
Proposed bounty: $400.00

### For all issues
[Keep _italic_ labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

[Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.]

_Estimated Budget of Task:_ **$[000]**  \
_Estimated Timeline Required to Complete the Task:_ **[days/weeks]**  \
_Measure of Completion:_ **[measure]**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by Keaycee** [comment]
Good job Jeremy, i just fixed the link. But the doc is not open for edit suggestions @jeremybeal11

**Comment by jeremybeal11** [comment]
@Keaycee  I'm sorry! still getting familiar to google Docs. here is the link for edits:

https://docs.google.com/document/d/1-MAwHS5gtOt1ugsG0Go0Uf23sgWgaa0lwPXQouUDf_U/edit?usp=sharing

**Comment by lapin7** [comment]
@jeremybeal11 
Please take some time and https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
Especially fill out [RAM-registration](out the RAM registration form https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform )

**Comment by jeremybeal11** [comment]
I have already registered and gone through the verification process. Is their something else I’m missing?

**Comment by dckc** [comment]
I'm pretty interested in learning about how RChain compares to things like Cardano. I'm struggling to get much out of the draft so far. Maybe it's because I'm too new to the field. I could go and read more of the Cardano materials, but that would seem to defeat the purpose of a document such as this.

Also, I see stuff about Cardano but nothing about RChain. Both Cardano and RChain aim to use proof-of-stake. Is either approach better than the other? Are they roughly equivalent?

Also, what's the intended audience? Is a google doc the goal, or is it a draft of an RChain blog item, or something else?

cc @pmoorman @ottermagically

**Comment by jeremybeal11** [comment]
@dckc the document that i submitted is just a claims document done in google docs to show Cardano major claims for market research and compare them to what RChain is currently doing. I’m new to this as well, and still learning more and more about RChain on the technical side. Long term speaking, i want to make this a article so people can look at it and learn about both platforms in a digestible manner. I really appreciate your insight and questions, and will make the corrections where needed. I will be working on more claims(articles) and this really helpful for me to understand how i need to write up the next article.

**Comment by pmoorman** [comment]
@jeremybeal11 I'm working with Jonathan and a few others to put together a coordinated Competitive Intelligence effort. 

I would love to invite you, but can't find you in Discord.  **What's your Discord handle?**

**Comment by jeremybeal11** [comment]
@pmoorman my discord name is: Germany

**Comment by dckc** [comment]
I'm surprised you close this. Was that on purpose?

**Comment by tucsonblockchain** [comment]
https://docs.google.com/document/d/1U8wAPG6_Myk4oRPN8CtZRD0WQWi99Y3HRb7fJZvkUu0/edit?usp=sharing Don't know if appropriate to drop this here, but allanc provided issue link. Want to see if anybody cares to contribute, or help take to next step, or if this should be shelved. Feel free to be honest or if it fits in with this issue, or if it does not. Thx!
